baseURL = "/"
languageCode = "en-us"
title = "Blockchain at UCSB"
theme = "kube"
Paginate = 4

[Params]
  RSSLink = "/index.xml"
  author = "Blockchain at UCSB" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"
  favicon = "img/blockchain-at-ucsb.png"
  banner = "img/blockchain-at-ucsb-banner.png"
  description = "Blockchain at UCSB (BCUCSB) is a community of students, entrepreneurs, and academics at UC Santa Barbara who have come together to educate and bring awareness about compelling blockchain technology and its applications. We host workshops, speaker events, innovation competitions, and socials to bring blockchain awareness to our local community."


[[menu.main]]
    name = "HOME"
    weight = -120
    url = "/"
[[menu.main]]
    name = "WHAT WE DO"
    weight = -110
    url = "/#what-we-do"
[[menu.main]]
    name = "ABOUT US"
    weight = -100
    url = "/#about-us"
[[menu.main]]
    name = "MEET THE TEAM"
    weight = -100
    url = "/#meet-the-team"
[[menu.main]]
    name = "EVENTS"
    weight = -90
    url = "/#events"
[[menu.main]]
    name = "CONTACT US"
    weight = -80
    url = "/#contact-us"
                      
